server.port=8080

mybatis.type-aliases-package=com.example.portfolio.domain
mybatis.configuration.map-underscore-to-camel-case=true

spring.application.name=portfolio

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1912#71c
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres